<?php

namespace LocationBundle\Repository;

/**
 * PointDistributionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointDistributionRepository extends \Doctrine\ORM\EntityRepository
{
}
