<?php

namespace LocationBundle\Repository;

/**
 * VeloLouerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VeloLouerRepository extends \Doctrine\ORM\EntityRepository
{
}
